"""Compiled control-to-standards crosswalk.

Generated from ``docs/shared/standards-crosswalk.md`` by
``scripts/gen_crosswalk.py``. Do not edit by hand: edit the document and run
``python scripts/gen_crosswalk.py``, then commit both files.

The enforcement service image does not contain ``docs/``, so the dashboard reads
the crosswalk from this module rather than from the document at runtime.

The mapping is indicative and carries the source document's scope caveat: these
controls support conformance with the referenced frameworks; they are not a
certification, an attestation, or a complete control set for any regulation.
"""

from __future__ import annotations

SOURCE_DOCUMENT = "docs/shared/standards-crosswalk.md"

CROSSWALK: tuple[dict[str, str], ...] = (
    {
        'code': 'A1',
        'name': 'NHI identity (per-agent principal)',
        'module': '`core/nhi_registry.py` + `cloud_adapters/<cloud>/identity.py`',
        'owasp': 'ASI — agent identity',
        'nist': 'GOVERN, MANAGE',
        'iso42001': 'A.9 roles & responsibilities',
        'eu_ai_act': 'Art.12 record-keeping (attribution)',
        'atlas': '—',
    },
    {
        'code': 'A2',
        'name': 'LLM-egress chokepoint',
        'module': '`cloud_adapters/<cloud>/gateway.py`',
        'owasp': 'ASI — excessive agency',
        'nist': 'MANAGE',
        'iso42001': 'A.6 lifecycle controls',
        'eu_ai_act': 'Art.15 robustness/cybersecurity',
        'atlas': 'LLM data leakage; exfiltration',
    },
    {
        'code': 'A3',
        'name': 'Egress allow-list',
        'module': '`galaxy_gov/shared/enforcement/egress_guard.py` + `cloud_adapters/<cloud>/egress.yaml`',
        'owasp': 'LLM05 / ASI',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': 'Exfiltration over web service',
    },
    {
        'code': 'B1',
        'name': 'Prompt-injection guard',
        'module': '`galaxy_gov/shared/enforcement/pipeline.py` (`agent_os.PromptInjectionDetector`)',
        'owasp': 'LLM01 / ASI-01',
        'nist': 'MEASURE, MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': 'Prompt injection (direct/indirect)',
    },
    {
        'code': 'B2',
        'name': 'Credential redactor',
        'module': '`galaxy_gov/shared/enforcement/pipeline.py` (`agent_os.CredentialRedactor`)',
        'owasp': 'LLM06 / LLM02:2025',
        'nist': 'MAP, MEASURE',
        'iso42001': 'A.7 data',
        'eu_ai_act': 'Art.10 data governance',
        'atlas': 'LLM data leakage',
    },
    {
        'code': 'B3',
        'name': 'Context-budget guard',
        'module': '`galaxy_gov/shared/enforcement/pipeline.py` (`agent_os.ContextScheduler`)',
        'owasp': 'LLM04 (unbounded consumption)',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': 'Denial of ML service / cost',
    },
    {
        'code': 'C1',
        'name': 'Capability guard (tool allow-list)',
        'module': '`galaxy_gov/shared/enforcement/pipeline.py` + `galaxy_gov/shared/enforcement/reasoning_guard.py`',
        'owasp': 'LLM08 (excessive agency)',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.14 human oversight',
        'atlas': 'LLM plugin/tool compromise',
    },
    {
        'code': 'C2',
        'name': 'Blocked-pattern scan (tool args)',
        'module': '`galaxy_gov/shared/enforcement/pipeline.py`',
        'owasp': 'LLM05 (improper output handling)',
        'nist': 'MEASURE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': '—',
    },
    {
        'code': 'I1',
        'name': 'A2A recipient allow-list',
        'module': '`core/a2a/dispatcher.py` + per-agent YAML',
        'owasp': 'ASI — multi-agent',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': '—',
    },
    {
        'code': 'I2',
        'name': 'A2A audited dispatch',
        'module': '`core/a2a/dispatcher.py` + `galaxy_gov/adapters/otel_audit_backend.py`',
        'owasp': 'ASI — multi-agent',
        'nist': 'GOVERN',
        'iso42001': 'A.9 logging',
        'eu_ai_act': 'Art.12 record-keeping',
        'atlas': '—',
    },
    {
        'code': 'D1–D4',
        'name': 'Data FGAC (ABAC allow / mask / row-filter)',
        'module': '`galaxy_gov/shared/enforcement/data_fgac.py` + `data_classification.py` (`agent_os.DataAccessEvaluator`)',
        'owasp': 'LLM02:2025 / ASI',
        'nist': 'MAP, MANAGE',
        'iso42001': 'A.7 data governance',
        'eu_ai_act': 'Art.10 data governance',
        'atlas': 'LLM data leakage',
    },
    {
        'code': 'D5',
        'name': 'FGAC store-side pushdown',
        'module': '`cloud_adapters/aws/data_fgac.py` (Lake Formation / Athena SQL)',
        'owasp': 'LLM02:2025',
        'nist': 'MANAGE',
        'iso42001': 'A.7',
        'eu_ai_act': 'Art.10',
        'atlas': 'LLM data leakage',
    },
    {
        'code': 'D6',
        'name': 'Data FGAC deny-all (no policy)',
        'module': '`galaxy_gov/shared/enforcement/data_fgac.py`',
        'owasp': 'LLM02:2025 / ASI',
        'nist': 'MANAGE',
        'iso42001': 'A.7',
        'eu_ai_act': 'Art.10',
        'atlas': '—',
    },
    {
        'code': 'K1',
        'name': 'Data-access drift detector',
        'module': '`galaxy_gov/shared/enforcement/data_drift.py` (`agent_sre.anomaly`)',
        'owasp': 'LLM02 / ASI',
        'nist': 'MEASURE (monitoring)',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15; Art.72 post-market monitoring',
        'atlas': 'Discover ML model behavior',
    },
    {
        'code': 'H1',
        'name': 'Reasoning-step guard (pre-exec CoT check)',
        'module': '`galaxy_gov/shared/enforcement/reasoning_guard.py`',
        'owasp': 'ASI — reasoning / LLM09',
        'nist': 'MEASURE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.14 human oversight',
        'atlas': '—',
    },
    {
        'code': 'H2',
        'name': 'CoT/CoVe reasoning trace (redacted)',
        'module': '`galaxy_gov/shared/enforcement/reasoning_trace.py`',
        'owasp': 'ASI — reasoning',
        'nist': 'MEASURE (explainability)',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.12 logging; Art.13 transparency',
        'atlas': '—',
    },
    {
        'code': 'M1',
        'name': 'Hash-chained audit ledger',
        'module': '`cloud_adapters/<cloud>/audit.py` + `core/trace_ledger.py`',
        'owasp': '—',
        'nist': 'GOVERN (accountability)',
        'iso42001': 'A.9 logging',
        'eu_ai_act': 'Art.12 record-keeping',
        'atlas': '—',
    },
    {
        'code': 'L1',
        'name': 'HITL escalation',
        'module': '`galaxy_gov/shared/enforcement/escalation_guard.py`',
        'owasp': 'ASI — human-in-the-loop',
        'nist': 'GOVERN, MANAGE',
        'iso42001': 'A.9',
        'eu_ai_act': 'Art.14 human oversight',
        'atlas': '—',
    },
    {
        'code': 'J1',
        'name': 'circuit breaker',
        'module': '',
        'owasp': 'LLM10 (unbounded consumption)',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': 'Denial of ML service',
    },
    {
        'code': 'B4',
        'name': 'semantic policy',
        'module': '',
        'owasp': 'LLM08 / ASI',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': 'LLM plugin/tool compromise',
    },
    {
        'code': 'C3',
        'name': 'secure codegen',
        'module': '',
        'owasp': 'LLM05 / LLM02',
        'nist': 'MEASURE, MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': '—',
    },
    {
        'code': 'C4',
        'name': 'secure exec (sandbox)',
        'module': '',
        'owasp': 'LLM08 / ASI',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.14, Art.15',
        'atlas': 'LLM plugin/tool compromise',
    },
    {
        'code': 'C5',
        'name': 'diff policy',
        'module': '',
        'owasp': 'LLM05',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': '—',
    },
    {
        'code': 'G1',
        'name': 'memory-write guard',
        'module': '',
        'owasp': 'LLM01 / LLM03 (data/model poisoning)',
        'nist': 'MEASURE, MANAGE',
        'iso42001': 'A.7 data',
        'eu_ai_act': 'Art.10, Art.15',
        'atlas': 'LLM data/model poisoning',
    },
    {
        'code': 'J2',
        'name': 'cost guard',
        'module': '',
        'owasp': 'LLM10 (unbounded consumption)',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': 'Denial of ML service / cost',
    },
    {
        'code': 'F1',
        'name': 'output PII redaction',
        'module': '',
        'owasp': 'LLM02:2025 (sensitive info disclosure)',
        'nist': 'MAP, MEASURE',
        'iso42001': 'A.7 data',
        'eu_ai_act': 'Art.10',
        'atlas': 'LLM data leakage',
    },
    {
        'code': 'E6',
        'name': 'MCP response scan',
        'module': '',
        'owasp': 'LLM01 (indirect injection) / ASI',
        'nist': 'MEASURE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': 'Prompt injection (indirect)',
    },
    {
        'code': 'L2',
        'name': 'transparency / disclosure',
        'module': '',
        'owasp': 'ASI — transparency',
        'nist': 'GOVERN',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.13 transparency; Art.14 oversight',
        'atlas': '—',
    },
    {
        'code': 'C6',
        'name': 'reversibility',
        'module': '',
        'owasp': 'LLM06 (excessive agency) / ASI',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.14 human oversight',
        'atlas': '—',
    },
    {
        'code': 'C7',
        'name': 'constraint graph',
        'module': '',
        'owasp': 'LLM08 (excessive agency)',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.14, Art.15',
        'atlas': 'LLM plugin/tool compromise',
    },
    {
        'code': 'E1',
        'name': 'MCP tool gateway',
        'module': '',
        'owasp': 'LLM08 / ASI',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.14, Art.15',
        'atlas': 'LLM plugin/tool compromise',
    },
    {
        'code': 'E2',
        'name': 'MCP rate limit',
        'module': '',
        'owasp': 'LLM10 (unbounded consumption)',
        'nist': 'MANAGE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': 'Denial of ML service',
    },
    {
        'code': 'E3',
        'name': 'MCP session auth',
        'module': '',
        'owasp': 'ASI — agent identity',
        'nist': 'GOVERN, MANAGE',
        'iso42001': 'A.9',
        'eu_ai_act': 'Art.12, Art.15',
        'atlas': '—',
    },
    {
        'code': 'E4',
        'name': 'MCP message signing',
        'module': '',
        'owasp': 'ASI — multi-agent integrity',
        'nist': 'GOVERN, MANAGE',
        'iso42001': 'A.9',
        'eu_ai_act': 'Art.12, Art.15',
        'atlas': '—',
    },
    {
        'code': 'E5',
        'name': 'MCP tool-definition screen',
        'module': '',
        'owasp': 'LLM01 / ASI (tool poisoning)',
        'nist': 'MEASURE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': 'Prompt injection (indirect)',
    },
    {
        'code': 'F2',
        'name': 'output content quality',
        'module': '',
        'owasp': 'LLM09 (misinformation)',
        'nist': 'MEASURE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.13 transparency; Art.15 accuracy',
        'atlas': '—',
    },
    {
        'code': 'N1',
        'name': 'SLO + error budget',
        'module': '',
        'owasp': '—',
        'nist': 'MEASURE, MANAGE',
        'iso42001': 'A.6, A.9',
        'eu_ai_act': 'Art.15; Art.72 monitoring',
        'atlas': '—',
    },
    {
        'code': 'N2',
        'name': 'accuracy declaration',
        'module': '',
        'owasp': '—',
        'nist': 'MEASURE (accuracy)',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.13 transparency; Art.15 accuracy',
        'atlas': '—',
    },
    {
        'code': 'N3',
        'name': 'eval suite',
        'module': '',
        'owasp': 'LLM09',
        'nist': 'MEASURE',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15',
        'atlas': '—',
    },
    {
        'code': 'N4',
        'name': 'golden-trace replay',
        'module': '',
        'owasp': '—',
        'nist': 'MEASURE (monitoring)',
        'iso42001': 'A.6, A.9',
        'eu_ai_act': 'Art.15; Art.72 monitoring',
        'atlas': '—',
    },
    {
        'code': 'N5',
        'name': 'SBOM (SPDX/CycloneDX)',
        'module': '',
        'owasp': 'LLM03 (supply chain)',
        'nist': 'GOVERN',
        'iso42001': 'A.10 third-party',
        'eu_ai_act': 'Art.15 cybersecurity',
        'atlas': 'ML supply chain compromise',
    },
    {
        'code': 'N6',
        'name': 'artifact signing (Ed25519)',
        'module': '',
        'owasp': 'LLM03 (supply chain)',
        'nist': 'GOVERN',
        'iso42001': 'A.10 third-party',
        'eu_ai_act': 'Art.15 cybersecurity',
        'atlas': 'ML supply chain compromise',
    },
    {
        'code': 'N7',
        'name': 'certification gate',
        'module': '',
        'owasp': '—',
        'nist': 'GOVERN (accountability)',
        'iso42001': 'A.9',
        'eu_ai_act': 'Art.17 quality management',
        'atlas': '—',
    },
    {
        'code': 'N8',
        'name': 'adversarial red-team',
        'module': '',
        'owasp': 'LLM01 / ASI',
        'nist': 'MEASURE (red-team)',
        'iso42001': 'A.6',
        'eu_ai_act': 'Art.15 robustness',
        'atlas': 'Prompt injection; evade ML model',
    },
)


def by_code() -> dict[str, dict[str, str]]:
    """The crosswalk keyed by control code."""
    return {row["code"]: row for row in CROSSWALK}
